apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-canary
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 7
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
    strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 100

