apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-canary
  # annotations:
  #   notifications.argoproj.io/subscribe.on-sync-succeeded.teams: "ArgoCD"
  #   notifications.argoproj.io/subscribe.on-sync-failed.teams: "ArgoCD"
  #   notifications.argoproj.io/subscribe.on-health-degraded.teams: "ArgoCD"
  #   notifications.argoproj.io/subscribe.on-deployed.teams: "ArgoCD"
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: myapp
  replicas: 10
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: argoproj/rollouts-demo:red
        ports:
        - containerPort: 8080
  strategy:
    canary:
      canaryService: myapp-canary
      stableService: myapp
      trafficRouting:
        istio:
          virtualService:
            name: my-virtualservice-argo
            routes:
            - primary
      steps:
      - setWeight: 30
      - pause:
          duration: 2m
      - setWeight: 50
      - pause:
          duration: 2m
      - setWeight: 100

