apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myapp-traefik
  labels:
    app: myapp-traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`test.com`) && PathPrefix(`/`)
     # middlewares:
        #- name: traefik-real-ip
        # - name: ip-whitelist
      services:
        - name: myapp
          port: 8080
  # tls:
  #   certResolver: default
